# thrly
#
# use symlinks to link to $HOME/.config/alacritty/alacritty.toml

[env]
TERM = "xterm-256color"

[window]

opacity = 0.8
blur = true

title = ""
dynamic_title = true

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size = 12.0

[mouse]

hide_when_typing = true

