-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
--
---- Disable ESLint LSP server and hide virtual text in Neovim
-- local isLspDiagnosticsVisible = true
-- vim.keymap.set("n", "<leader>lx", function()
--   isLspDiagnosticsVisible = not isLspDiagnosticsVisible
--   vim.diagnostic.config({
--     virtual_text = isLspDiagnosticsVisible,
--     underline = isLspDiagnosticsVisible,
--   })
-- end, { desc = "Toggle LSP" })
